services:
  frontend:
    build: 
      context: ../basic/frontend/
      dockerfile: ../../docker/frontend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
  backend:
    build:
      context: ../basic/backend/
      dockerfile: ../../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USE_DATABASE=true
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=backend_db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: